version: "3"
services:
  todo:
    image: "node:10-alpine"
    user: "node"
    working_dir: "/home/node/app"
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongodb/todo
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:8080"
    command: "./docker-runner.sh"
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb-data:/data/db"
